{
 "title": "Sougui MLOps Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Model Health - Accuracy ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "ml_model_metric_value", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "API Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "http_errors_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Ouma Prediction Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(http_request_duration_seconds_sum{handler=\"/ouma/predict/one\"})\r\n/\r\nsum(http_request_duration_seconds_count{handler=\"/ouma/predict/one\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sougui Prediction Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "http_requests_total{handler=\"/ouma/predict/one\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Traffic - Requests per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    { "expr": "rate(http_requests_total[1m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Service Health",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    { "expr": "up", "legendFormat": "__auto" }
   ]
  }
 ]
}